### ISSUE TITLE
Update config.json to reflect CSBC/PS-ON data model schema

### ISSUE THREAD

**Issue by vpchung** [mc2-center/data_curator#2]
Currently, the DCA is showing the default metadata templates for schematic:

![Screen Shot 2022-06-01 at 4 20 08 PM](https://user-images.githubusercontent.com/9377970/171517140-d34fcac9-e4e0-4274-b896-58157a0ce7ac.png)

Until the GH workflow is available that will automatically update `config.json` according to the underlying JSON-LD file, `config.json` should manually be updated to reflect the data models for CSBC/PS-ON.

**Comment by vpchung** [comment]
@brynnz22 did you want to tackle this?  Otherwise, I'd be more than happy to!  lmk.

**Comment by brynnz22** [comment]
@vpchung Yes I will do it tomorrow!

**Comment by brynnz22** [comment]
Update has been deployed to DCA staging.

![Screen Shot 2022-06-03 at 1 46 52 PM](https://user-images.githubusercontent.com/46435419/171950594-285945ca-9b13-4fac-9db4-7afa1c843442.png)
