### ISSUE TITLE
Incorrect manifest templates listed

### ISSUE THREAD

**Issue by vpchung** [mc2-center/data_curator#27]
The DCA is currently listing manifest templates that are not listed in [`www/config.json`](https://github.com/mc2-center/data_curator/blob/main/www/config.json):

![manifest-templates](https://user-images.githubusercontent.com/9377970/201263245-8a6564b3-eff9-43d0-be2f-35dfecb3633f.png)

I have tried re-deploying the app, both staging and testing, with little success of updating the listed templates.

CC: @brynnz22

**Comment by vpchung** [comment]
After some digging, I realize the apps have been deployed as `mc2_data_curator-*` -- I was still checking `csbc_data_curator`, which explains why an update was not seen.

Unfortunately, the `mc2_data_curator-*` apps are not working, so unable to check 🙃  I'll try reverting back to `csbc_data_curator` to see if an update will occur.

**Comment by vpchung** [comment]
**Update**
Redeployed the apps with appName = `csbc_data_curator` but looks like the listed manifest types is still incorrect:

![Screen Shot 2022-11-11 at 11 00 18 AM](https://user-images.githubusercontent.com/9377970/201411850-b788755e-15f3-4bb6-8dbe-327456519a02.png)

^ this is from the `testing` app; staging is still broken so I can't check that. Based on the [deployment logic](https://github.com/mc2-center/data_curator/blob/64ce7b43e870b74e8a215a650428012e23383a6e/.github/workflows/shinyapps_deploy.yml#L113), the prod app will only be re-deployed if I create a tag with `v*.*.*`, so haven't checked that either.

**Comment by afwillia** [comment]
@vpchung the deployment workflow regenerates the `www/config` file based off what's in the data model github repo. This is the specific code in `.github/workflows/shiny_deploy.yml`

``` 
 - name: Set Configurations for Data Model
        shell: bash
        run: |
          source .venv/bin/activate
          # download the data models and create config.json
          python3 .github/config_schema.py \
            -c schematic_config.yml \
            --service_repo 'Sage-Bionetworks/schematic' \
            --overwrite
```

To avoid updating the data model, it might be possible to remove the `--overwrite` flag above.

**Comment by vpchung** [comment]
@afwillia oh, I see.  So this [config](https://github.com/mc2-center/data-models/blob/main/config.yml)?

**Comment by afwillia** [comment]
@vpchung no, it actually uses the data model itself https://github.com/mc2-center/data-models/blob/main/mc2.model.csv. I believe record with a non-missing `dependsOn Component` will show up in the `www/config.json` / template menu

**Comment by brynnz22** [comment]
@afwillia is there a way it can reference that [config.json](https://github.com/mc2-center/data_curator/blob/main/www/config.json) file again? We don't need every single component in the data model that has a `dependsOn Component` to show up in the templates in the DCA. Many of these in our data model are for admin only and we do not want them as options for the public.

**Comment by afwillia** [comment]
@brynnz22 yes, I'll remove the script that creates a new config.json from the workflow, so it will use the existing one in the repo.

**Comment by vpchung** [comment]
Thanks, @afwillia ! 🎉

**Comment by brynnz22** [comment]
@afwillia Thank you!

**Comment by vpchung** [comment]
Deployment workflow has been updated; app will now use the config.json file that is defined in the app itself.

Closing issue!
