### ISSUE TITLE
Warning: Error in py_run_file_impl: ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by afwillia** [mc2-center/data_curator#32]
**Describe the bug**
Warning: Error in py_run_file_impl: ModuleNotFoundError: No module named 'pkg_resources'

In shinyapps.io console

**Comment by vpchung** [comment]
### Steps Taken
1. Updated the app name on line 99 in [`.github/workflows/shinyapps_deploy.yml`](https://github.com/mc2-center/data_curator/blob/5772b29abb4327c67d82d75298a75c4723c182d0/.github/workflows/shinyapps_deploy.yml#L99) from `"csbc_data_curator"` to `"mc2_data_curator"`
2. After the [re-deployment](https://github.com/mc2-center/data_curator/actions/runs/3526518086/workflow) is successful, I went to the [app](https://sagebio.shinyapps.io/mc2_data_curator-staging/) to check
3. Error received during the Waiter loading screen:
    ![Screen Shot 2022-11-22 at 12 54 49 PM](https://user-images.githubusercontent.com/9377970/203419301-e4176383-111b-4b04-af5c-9964e0f2f813.png)

Upon @afwillia 's suggestion, I tried the redeployment with both `testing` and `staging`, but both versions are unable to load.

**Comment by afwillia** [comment]
This was fixed by setting this instance size in the app's dashboard to xxxlarge. The default large is too small for the app.
